development:
  adapter: postgresql
  encoding: unicode
  database: semenistyy_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: semenistyy_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: semenistyy_production
  pool: 5