development:
  adapter: postgresql
  encoding: unicode
  database: simplepm_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: simplepm_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: simplepm_prod
  pool: 5